"use client";

import { motion } from "framer-motion";
import { FileText } from "lucide-react";

const SECTIONS = [
  {
    title: "1. Acceptance of Terms",
    content: [
      "By accessing or using RecME, you agree to be bound by these Terms of Service. If you do not agree, please do not use the service.",
      "You must be at least 13 years old to use RecME.",
    ],
  },
  {
    title: "2. Your Account",
    content: [
      "You are responsible for maintaining the confidentiality of your account credentials.",
      "You are responsible for all activity that occurs under your account.",
      "You must provide accurate information when creating an account and keep it up to date.",
      "You may delete your account at any time from your Profile page. Deletion is permanent and cannot be undone.",
    ],
  },
  {
    title: "3. Acceptable Use",
    content: [
      "You may not use RecME for any illegal or unauthorised purpose.",
      "You may not attempt to gain unauthorised access to any part of the service or its systems.",
      "You may not use automated scripts or bots to scrape or interact with the service at scale.",
      "You may not upload or submit any content that is harmful, abusive, or violates any law.",
    ],
  },
  {
    title: "4. Intellectual Property",
    content: [
      "The RecME platform, including its design, code, and AI recommendation engine, is owned by us and protected by intellectual property law.",
      "Movie metadata, posters, and images are sourced from TMDB and OMDb under their respective terms of use. RecME is not affiliated with or endorsed by TMDB or OMDb.",
      "You may not reproduce, distribute, or create derivative works of RecME without explicit written permission.",
    ],
  },
  {
    title: "5. Third-Party Content",
    content: [
      "RecME displays movie data from TMDB and OMDb. We do not guarantee the accuracy, completeness, or timeliness of this data.",
      "Links or references to third-party content do not constitute endorsement.",
    ],
  },
  {
    title: "6. Recommendations Disclaimer",
    content: [
      "Movie recommendations are generated by an AI system and are provided for entertainment purposes only.",
      "We make no guarantees about the suitability, quality, or availability of any recommended film.",
    ],
  },
  {
    title: "7. Limitation of Liability",
    content: [
      "RecME is provided on an \"as is\" and \"as available\" basis without warranties of any kind.",
      "We are not liable for any indirect, incidental, or consequential damages arising from your use of the service.",
      "Our total liability to you for any claims shall not exceed the amount you paid us in the past 12 months (which may be zero, as the service is currently free).",
    ],
  },
  {
    title: "8. Termination",
    content: [
      "We reserve the right to suspend or terminate your account at any time if we believe you have violated these Terms of Service.",
      "You may terminate your account at any time by using the Delete Account feature in your Profile page.",
    ],
  },
  {
    title: "9. Changes to These Terms",
    content: [
      "We may revise these Terms from time to time. Updated terms will be posted on this page with a new effective date.",
      "Continued use of RecME after changes are posted constitutes your acceptance of the updated terms.",
    ],
  },
  {
    title: "10. Contact",
    content: [
      "If you have questions about these Terms, please contact us at reddyvaru12@gmail.com.",
    ],
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-transparent flex flex-col">
      <main className="flex-1 max-w-5xl mx-auto px-6 py-20 w-full">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4 }}
        >
          {/* Header */}
          <div className="flex items-center gap-3 mb-2">
            <div className="w-10 h-10 rounded-2xl bg-purple-100 dark:bg-purple-900/30 flex items-center justify-center">
              <FileText className="w-5 h-5 text-purple-600 dark:text-purple-400" />
            </div>
            <h1 className="text-3xl font-black text-gray-900 dark:text-white tracking-tight">
              Terms of Service
            </h1>
          </div>
          <p className="text-sm text-gray-400 dark:text-zinc-500 mb-10">
            Effective date: March 22, 2026 · Last updated: March 22, 2026
          </p>

          <p className="text-sm text-gray-600 dark:text-zinc-400 leading-relaxed mb-10">
            Please read these Terms of Service carefully before using RecME. These terms govern
            your access to and use of the RecME platform, including its AI-powered movie
            recommendation features.
          </p>

          <div className="space-y-8">
            {SECTIONS.map((section) => (
              <div
                key={section.title}
                className="bg-white dark:bg-zinc-900 rounded-2xl border border-gray-100 dark:border-white/5 p-6 shadow-sm"
              >
                <h2 className="text-base font-black text-gray-900 dark:text-white mb-4">
                  {section.title}
                </h2>
                <ul className="space-y-2">
                  {section.content.map((item, i) => (
                    <li
                      key={i}
                      className="text-sm text-gray-600 dark:text-zinc-400 leading-relaxed flex gap-2"
                    >
                      <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-purple-400 shrink-0" />
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </motion.div>
      </main>
    </div>
  );
}
